version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - teachua_net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        PORT: 8080
    container_name: backend
    volumes:
      - ./backend/setenv.sh:/app/setenv.sh:ro
    environment:
      SPRING_PROFILES_ACTIVE: dev
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - teachua_net

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: pmp2025
      POSTGRES_PASSWORD: Pmp#2025
      POSTGRES_DB: teachua
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - teachua_net

volumes:
  db-data:

networks:
  teachua_net: