---
- name: Deploy Frontend Application to GCP
  hosts: gcp_group_instance_front_group
  become: yes
  gather_facts: true
  
  vars:
    service_account_file: gcp_client_hsecret.json
    ansible_ssh_common_args: '-i ~/.ssh/google_compute_engine -J devops@bastion.us-central1-c.teachua-6147'
    backend_url: "http://34.110.208.19"  # Backend proxy URL
    
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Node.js repository
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
      args:
        creates: /etc/apt/sources.list.d/nodesource.list

    - name: Install required packages
      apt:
        name:
          - nodejs
          - git
          - nginx
          - build-essential
        state: present

    - name: Create application directory
      file:
        path: /opt/teachua
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Sync frontend code to remote server
      synchronize:
        src: ../frontend/
        dest: /opt/teachua/frontend/
        recursive: yes
        delete: yes
        compress: yes
        rsync_path: "sudo rsync"
        owner: no
        group: no

    - name: Set ownership of frontend directory
      file:
        path: /opt/teachua/frontend
        owner: www-data
        group: www-data
        recurse: yes

    - name: Create .env file for production
      copy:
        dest: /opt/teachua/frontend/.env.production
        content: |
          REACT_APP_ROOT_SERVER={{ backend_url }}
          REACT_APP_NAME=TeachUA
          NODE_ENV=production

    - name: Install npm dependencies
      shell: |
        cd /opt/teachua/frontend
        npm install --legacy-peer-deps
      become_user: www-data
      environment:
        NODE_OPTIONS: "--max-old-space-size=2048"

    - name: Build frontend application
      shell: |
        cd /opt/teachua/frontend
        npm run build
      become_user: www-data
      environment:
        NODE_OPTIONS: "--max-old-space-size=2048"

    - name: Create nginx configuration
      copy:
        dest: /etc/nginx/sites-available/default
        content: |
          server {
              listen 80;
              server_name _;
              
              root /opt/teachua/frontend/build;
              index index.html;
              
              # Frontend routes
              location / {
                  try_files $uri $uri/ /index.html;
              }
              
              # Proxy API requests to backend
              location /api {
                  proxy_pass {{ backend_url }};
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
                  
                  # Timeouts
                  proxy_connect_timeout 60s;
                  proxy_send_timeout 60s;
                  proxy_read_timeout 60s;
              }
              
              # OAuth2 endpoints
              location /oauth2 {
                  proxy_pass {{ backend_url }};
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
              
              # File upload endpoint
              location /upload {
                  proxy_pass {{ backend_url }};
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
                  
                  # Increase body size for file uploads
                  client_max_body_size 20M;
              }
              
              # Swagger UI
              location /swagger-ui {
                  proxy_pass {{ backend_url }};
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
              
              # Static assets caching
              location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
                  expires 1y;
                  add_header Cache-Control "public, immutable";
              }
          }

    - name: Test nginx configuration
      shell: nginx -t

    - name: Restart nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes

    - name: Ensure nginx is running
      systemd:
        name: nginx
        state: started
        enabled: yes 