---
- name: Quick Test Setup
  hosts: gcp_group_instance_back_group
  become: yes
  
  tasks:
    - name: Install basic packages
      apt:
        name:
          - nginx
          - curl
        state: present
        update_cache: yes

    - name: Create test page
      copy:
        dest: /var/www/html/index.html
        content: |
          <html>
          <body>
            <h1>Backend Server Ready</h1>
            <p>Time: {{ ansible_date_time.iso8601 }}</p>
            <p>Server: {{ inventory_hostname }}</p>
          </body>
          </html>

    - name: Start nginx
      systemd:
        name: nginx
        state: started
        enabled: yes

- name: Quick Test Frontend Setup  
  hosts: gcp_group_instance_front_group
  become: yes
  
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Create test frontend page
      copy:
        dest: /var/www/html/index.html
        content: |
          <html>
          <body>
            <h1>Frontend Server Ready</h1>
            <p>Time: {{ ansible_date_time.iso8601 }}</p>
            <p>Server: {{ inventory_hostname }}</p>
            <p>Backend: <a href="http://34.110.208.19">http://34.110.208.19</a></p>
          </body>
          </html>

    - name: Start nginx
      systemd:
        name: nginx
        state: started
        enabled: yes 