- name: Ensure required packages are installed
  package:
    name: "{{ packages }}"
    state: present
  become: true
- name: Copy database dump file to /tmp
  copy:
    src: "{{ dump_file }}"
    dest: "/tmp/{{ dump_file }}"
    mode: '0644'

- name: Create application database user
  community.postgresql.postgresql_user:
    login_host: "{{ db_host }}"
    login_port: "{{ db_port }}"
    login_user: "{{ postgres_admin_user }}"
    login_password: "{{ postgres_admin_password }}"
    login_db: "postgres"
    ssl_mode: require
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    encrypted: yes
    state: present

- name: Create application database
  community.postgresql.postgresql_db:
    login_host: "{{ db_host }}"
    login_port: "{{ db_port }}"
    login_user: "{{ postgres_admin_user }}"
    login_password: "{{ postgres_admin_password }}"
    maintenance_db: "postgres"
    ssl_mode: require
    name: "{{ db_name }}"
    state: present

- name: Restore database from dump
  shell: |
    PGPASSWORD="{{ postgres_admin_password }}" \
    psql "host={{ db_host }} \
          port={{ db_port }} \
          dbname={{ db_name }} \
          user={{ postgres_admin_user }} \
          sslmode=require" \
       < /tmp/{{ dump_file }}
  args:
    executable: /bin/bash
 


