on:
  push:
  pull_request:
    types: [opened, reopened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram notification
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d text="🚀 ${{ github.actor }} зробив апдейт і запушив зміни в ${{ github.repository }}. Глянь що там: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}"
          elif [[ "${{ github.event_name }}" == "pull_request" && "${{ github.event.action }}" == "opened" ]]; then
            curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d text="🔔 ${{ github.actor }} створив Pull Request в ${{ github.base_ref || 'dev' }}. Будь ласка, зроби апрув: ${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.pull_request.number }}"
          elif [[ "${{ github.event_name }}" == "pull_request" && "${{ github.event.action }}" == "closed" && "${{ github.event.pull_request.merged }}" == "true" ]]; then
            curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d text="✅ ${{ github.actor }} змерджив Pull Request в ${{ github.base_ref || 'dev' }}: ${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.pull_request.number }}"
          fi
